### PR TITLE
Add some more stuff to Cars

### PR DESCRIPTION
**Pull request by SteveBarnett**

### CODE REVIEW

**Comment by SteveBarnett** [comment]
@avermeulen Some quick ideas for adding more to the Kata.

**Comment by SteveBarnett** [comment]
@avermeulen Ping!

**Comment by SteveBarnett** [comment]
@avermeulen Ping!

**Comment by avermeulen** [comment]
@SteveBarnett What I was wondering about this in the past who will be doing the painting? The Ferry class which felt funny from an encapsulation point of few.

Changing the passengers I like alot. Quite fiddly potentially but nice!

**Comment by SteveBarnett** [comment]
@avermeulen Can you please clarify: what are the TODOs now? Ta!

**Comment by SteveBarnett** [comment]
@avermeulen Ping!

**Comment by avermeulen** [comment]
@SteveBarnett Will the Ferry have a `paint` method that takes a `color` and a `Car` as parameters? And changing cars how would it look like - a `switch` method on a Car - taking in `Car` and a passenger number to switch?

**Pull request closed without merging**
